# Generated by Django 3.1.7 on 2021-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_inquiry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='description',
            field=models.TextField(verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Din epost'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Ditt navn'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tittel'),
        ),
    ]
