# Generated by Django 3.1.7 on 2021-03-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20210321_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
