# Generated by Django 3.1.7 on 2021-03-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_lecture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.FileField(null=True, upload_to='static/img/'),
        ),
    ]
