# Generated by Django 3.1.7 on 2021-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0008_auto_20210321_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Hendvendelse', 'verbose_name_plural': 'Hendvendelse'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Modul', 'verbose_name_plural': 'Moduler'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Din epost'),
        ),
    ]
