# Generated by Django 3.1.7 on 2021-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_auto_20210321_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='author',
            field=models.CharField(default='Marie Samuelsen', max_length=128),
        ),
    ]
