# Generated by Django 3.1.7 on 2021-03-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_lecture_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='author',
        ),
    ]
