# Generated by Django 3.1.7 on 2021-03-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0011_remove_lecture_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
